on:
  push:
    branches:
      - main

jobs:
  test-az-login:
    runs-on: self-hosted
    inputs:
      region:
        description: 'Specify the region'
        required: true
        type: string
        default: 'asse'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        run: az login --identity --username ${{secrets.TEST_SECRET01}}

      - name: Conditional Azure Login
        if: ${{ needs.test-az-login.outputs.region == 'asea' }}
        run: az login --identity --username ${{secrets.TEST_SECRET02}}
