name: build_deploy_aks
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Please select your cluster'
        required: true
        type: choice
        options:
         - asse
         - asea
jobs:
  test-az-login:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.TEST_SECRET01}}

      - name: Conditional Azure Login
        if: ${{ inputs.region == 'asea' }}
        uses: azure/login@v1
        with:
          creds: ${{secrets.TEST_SECRET02}}
        
