on:
  workflow_dispatch:
    branches:
      - main
jobs:
  test-az-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set GITHUB_ENV
        run: |
          echo "TEST_SECRET01=${{ secrets.TEST_SECRET01 }}" >> $GITHUB_ENV
          echo "TEST_SECRET02=${{ secrets.TEST_SECRET02 }}" >> $GITHUB_ENV
