on:
  push:
    branches:
      - main
jobs:
  test-az-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login via Azure CLI
        id: az-login
        run: |
          az login --identity --username ${{ secrets.TEST_IDENTITY01 }}
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
