name: test-az-login
on:
  workflow_dispatch:
  
jobs:
  test-az-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: 'Secrets Substitution'
        uses: microsoft/variable-substitution@v1
        with:
          files: '.github/values.yaml'
        env:
          test.key: ${{ secrets.TEST_IDENTITY01 }} # Enter base64 encoded in Github Secret

      - name: check secrets
        run: |
          cat '.github/values.yaml' | sed 's/./& /g'


