name: test-az-login
on:
  workflow_dispatch:
  
jobs:
  test-az-login:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo secret
        run: |
          echo ${{ secrets.TEST_IDENTITY01 }}
