name: Your Workflow Name

on:
  push:
    branches:
      - main

inputs:
  region:
    description: 'Specify the region'
    required: true
    type: string
    default: 'asse'

jobs:
  test-az-login:
    runs-on: self-hosted

    env:
      REGION: ${{ github.event.inputs.region }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        run: az login --identity --username ${{secrets.TEST_SECRET01}}

      - name: Conditional Azure Login
        if: ${{ env.REGION == 'asea' }}
        run: az login --identity --username ${{secrets.TEST_SECRET02}}
