name: test-az-login
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Please select your region'
        required: true
        type: choice
        options:
          - asse
          - asea

jobs:
  test-az-login:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login via Azure CLI
        id: az-login
        run: |
          if [ "${{ inputs.region }}" == 'asea' ]; then
            az login --identity --username "${{ secrets.TEST_SECRET01 }}"
          else
            az login --identity --username "${{ secrets.TEST_SECRET02 }}"
        
