name: test-az-login
on:
  workflow_dispatch:
  
jobs:
  test-az-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo secret
        env:
          TEST_IDENTITY01: ${{ secrets.TEST_IDENTITY01 }}
        run: |
          echo $TEST_IDENTITY01 >> secrets.txt
          
      - name: check secrets
        run: |
          cat secrets.txt
