on:
  push:
    branches:
      - main
    inputs:
      test:
        required: true
        type: string
        default: TEST
jobs:
  test-az-login:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set secret name
        id: set-secret-name
        run: echo "SECRET_NAME=${{ inputs.test }}_IDENTITY01" >> $GITHUB_ENV

      - name: Login via Azure CLI
        id: az-login
        run: |
          az login --identity --username ${{ env.SECRET_NAME }}

