on:
  push:
    branches:
      - main
jobs:
  test-az-login:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ runner.os == 'Linux' && secrets.TEST_SECRET01 || runner.os == 'self-hosted' && secrets.TEST_SECRET02 }}

