on:
  push:
    branches:
      - main
    inputs:
      CREDENTIALS:
        required: true
        type: string
        default: CREDENTIALS
jobs:
  sync-keyvault:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Azure CLI version
      run: az --version

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_${{inputs.CREDENTIALS}} }}

    - name: Sync secrets
      run: |
        srcKeyVault="kunlawitvault"
        destKeyVault="kunlawitvault02"
        
        # Get list of secrets from source Key Vault
        secrets=$(az keyvault secret list --vault-name $srcKeyVault --query '[].name' --output tsv)

        # Loop through secrets and copy to destination Key Vault
        for secret in $secrets
        do
          # Get secret value from source Key Vault
          secretValue=$(az keyvault secret show --name $secret --vault-name $srcKeyVault --query 'value' --output tsv)
          echo "::add-mask::$secretValue"
          
          # Set secret in destination Key Vault
          az keyvault secret set --vault-name $destKeyVault --name $secret --value "$secretValue"
          echo "
