on:
  push:
    branches:
      - main

jobs:
  sync-keyvault:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Azure CLI version
      run: az --version

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        

    - name: Sync Key Vault Secrets
      run: |
        # Source Key Vault
        sourceKeyVault="kunlawitvault"
        
        # Destination Key Vault
        destinationKeyVault="kunlawitvault02"

        # List secrets from source Key Vault
        secrets=$(az keyvault secret list --vault-name $sourceKeyVault --query '[].name' --output tsv)

        # Loop through secrets and copy to destination Key Vault
        for secret in $secrets; do
          az keyvault secret show --vault-name $sourceKeyVault --name $secret --query "{value: value, contentType: contentType, tags: tags, enabled: attributes.enabled, notBefore: attributes.notBefore, expires: attributes.expires}" --output json |
          az keyvault secret set --vault-name $destinationKeyVault --name $secret --output none
        done

      env:
        AZURE_KEYVAULT_URI: https://$sourceKeyVault.vault.azure.net/

          # Set the secret status separately using az keyvault secret set-attributes
          az keyvault secret set-attributes --vault-name $destinationKeyVault --name $secret --enabled $secretStatus > /dev/null
        done
