name: Sync Key Vault Data

on:
  push:
    branches:
      - main

jobs:
  sync-keyvault:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Sync data from source to destination Key Vault
      run: |
        sourceKeyVault=kunlawitvault
        destinationKeyVault=kunlawitvault02

        # Get a list of secrets in the source Key Vault
        sourceSecrets=$(az keyvault secret list --vault-name $sourceKeyVault --query '[].name' -o tsv)

        # Loop through each secret and copy it to the destination Key Vault
        for secretName in $sourceSecrets; do
          az keyvault secret show --vault-name $sourceKeyVault --name $secretName --query '[value]' --o tsv | \
            az keyvault secret set --vault-name $destinationKeyVault --name $secretName --value @- --o none
        done

    - name: Logout from Azure
      run: az logout
