on:
  push:
    branches:
      - main

jobs:
  sync-keyvault:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Azure CLI version
      run: az --version

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Sync Key Vault Secrets
      run: |
        # Replace the placeholder values with your actual Key Vault names
        sourceKeyVault="kunlawitvault"
        destinationKeyVault="kunlawitvault02"

        # Fetch the list of secret names from the source Key Vault
        secrets=$(az keyvault secret list --vault-name $sourceKeyVault --query "[].name" --output tsv)

        # Loop through the secrets and sync them to the destination Key Vault
        for secret in $secrets; do
          echo "Syncing secret: $secret"
          secretId=$(az keyvault secret show --vault-name $sourceKeyVault --name $secret --query "id" --output tsv)
          secretType=$(az keyvault secret show --id $secretId --query "contentType" --output tsv)
          secretExpiration=$(az keyvault secret show --id $secretId --query "expires" --output tsv || echo "")
          secretTags=$(az keyvault secret show --id $secretId --query "tags" --output json)
          secretStatus=$(az keyvault secret show --id $secretId --query "enabled" --output tsv)
          
          # Mask the actual secret value
          secretValue="***"

          # Set the secret in the destination Key Vault
          if [ -z "$secretExpiration" ]; then
            az keyvault secret set --vault-name $destinationKeyVault --name $secret --value "$secretValue" --content-type "$secretType" --tags "$secretTags" --enabled "$secretStatus" > /dev/null
          else
            az keyvault secret set --vault-name $destinationKeyVault --name $secret --value "$secretValue" --content-type "$secretType" --expires "$secretExpiration" --tags "$secretTags" --enabled "$secretStatus" > /dev/null
          fi
        done
