on:
  push:
    branches:
      - main

jobs:
  sync-keyvault:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Azure CLI version
      run: az --version

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Sync Key Vault Secrets
      run: |
        # Source Key Vault
        sourceKeyVault="kunlawitvault"
        
        # Destination Key Vault
        destinationKeyVault="kunlawitvault02"

        # List secrets from source Key Vault
        secrets=$(az keyvault secret list --vault-name $sourceKeyVault --query '[].name' --output tsv)

        # Loop through secrets and copy to destination Key Vault
        for secret in $secrets; do
          secretProperties=$(az keyvault secret show --vault-name $sourceKeyVault --name $secret --query "{value: value, contentType: contentType, tags: tags, enabled: attributes.enabled, notBefore: attributes.notBefore, expires: attributes.expires}" --output json)
          value=$(echo $secretProperties | jq -r '.value')
          contentType=$(echo $secretProperties | jq -r '.contentType')
          tags=$(echo $secretProperties | jq -r '.tags')
          enabled=$(echo $secretProperties | jq -r '.enabled')
          notBefore=$(echo $secretProperties | jq -r '.notBefore')
          expires=$(echo $secretProperties | jq -r '.expires')

          # Format dates
          notBefore=$(date -u -d "$notBefore" '+%Y-%m-%dT%H:%M:%SZ')
          expires=$(date -u -d "$expires" '+%Y-%m-%dT%H:%M:%SZ')

          az keyvault secret set --vault-name $destinationKeyVault --name $secret --value "$value" --content-type "$contentType" --tags "$tags" --enabled $enabled --not-before "$notBefore" --expires "$expires" --output none
        done

      env:
        AZURE_KEYVAULT_URI: https://$sourceKeyVault.vault.azure.net/
