on:
  push:
    branches:
      - main

jobs:
  sync-keyvault:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Azure CLI version
      run: az --version

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Sync Key Vault Secrets
      run: |
        # Replace the placeholder values with your actual Key Vault names
        sourceKeyVault="kunlawitvault"
        destinationKeyVault="kunlawitvault02"

        # Fetch the list of secret names from the source Key Vault
        secrets=$(az keyvault secret list --vault-name $sourceKeyVault --query "[].name" --output tsv)

        # Loop through the secrets and sync them to the destination Key Vault
        for secret in $secrets; do
          echo "Syncing secret: $secret"
          az keyvault secret show --vault-name $sourceKeyVault --name $secret --query "id" --output tsv | xargs az keyvault secret show --id --vault-name $sourceKeyVault --name $secret --query "id,contentType,tags,enabled,expires,keyId,managed,notBefore,recoverableDays" --output table
          az keyvault secret set --vault-name $destinationKeyVault --name $secret --value "$(az keyvault secret show --vault-name $sourceKeyVault --name $secret --query "value" --output tsv)"
        done
