name: test-new-ids

on:
  workflow_dispatch:
  
env:
  ENVIRONMENT: "asea"

jobs:
  test-path-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Deploy path"
        run: |
          for service in ./config/config01/*; do 
              echo "Service path: $service"
                
            done
          done
