on:
  workflow_dispatch:
    branches:
      - main
jobs:
  sync-keyvault:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set GITHUB_ENV
      run: |
          # Format AZURE_CREDENTIALS as JSON and append to GITHUB_ENV
          echo "creds=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -c)" >> $GITHUB_ENV

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ env.creds }}
