name: test-new-ids

on:
  workflow_dispatch:
  
env:
  ENVIRONMENT: "asea"

jobs:
  test-path-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Deploy path"
        run: |
          for service in .github/config/config01/*; do 
            service="${service##*/}"
            for filepath in .github/config/config01/${service}; do
                filename="${filepath##*/}"
                basename="${filename%.*}"
            echo $filepath

            echo $filename

            echo $basename
                
            done
          done

