name: test-new-ids

on:
  workflow_dispatch:
  
env:
  ENVIRONMENT: "asea"

jobs:
  test-path-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Deploy path"
        run: |
          for filepath in ./config/config01/*; do
            if [ -f "$filepath" ]; then
              filename=$(basename "$filepath")
              echo "Processing file: $filename"
              # Your further operations with each file can go here
            fi
          done


