name: test-new-ids

on:
  workflow_dispatch:
  
jobs:
  test-path-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Deploy path"
        run: |
          for filepath_outer in ./config/config01/*; do
            for filepath_inner in "$filepath_outer"/*; do
              echo "File: $(basename "$filepath_inner")"
              echo "Path: $filepath_inner"
            done
          done



