name: List .github/config

on:
  workflow_dispatch:

jobs:
  list_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: List .github/config directory
      run: ls -R .github/config

